language: ruby

sudo: true

matrix:
  include:
    - os: osx
      osx_image: xcode9
      rvm: system
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gem

install: true # skip install step

before_script:
  - . ci/travis/before_script.sh

script:
  - . ci/travis/script.sh
